version: "3.3"

services:

  mongodb:
    image: mongo:4.4
    container_name: cleardekho_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: cleardekho_backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/cleardekho
      JWT_SECRET: clearvision_secret_key
      _PORT: 8080
      _PRIVATE_KEY: clearvision_secret_key

  frontend:
    build: ./frontend
    container_name: cleardekho_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
